import json
import base64

# base64
#  ある人が頭によぎった
# b64encoded_data = 'lAEAAAAAAABEMyIRFAAAAAAADgAKAAQAAAAAAAAACQAOAAAAZAAAAAABXgAcABAADAAAAAAAAAAAAAAAAAAAAAAAGAAXAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAHAF4AAAAAAAABFAAAACQAAABEAAAAAAAAARAAAABg////ZP///2j///9G////AAIIJgEAAAAEAAAAFgAAAE5vdG9TZXJpZkpQLUV4dHJhTGlnaHQAAAEAAAAMAAAACAAMAAQACAAIAAAAjAAAADgAAAA0ABgAAAAAABQAAAAQAA8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAQANAAAABgAAAAcAAAAAAAAASQAAAA0AAAABAAEAAQAAAAEAAYABAAAAAAACgAKAAcACAAJAAoAAAAAAAACCCYKAAgABQAGAAcACgAAAADq3c8eAAAA44GC44KL5Lq644GM6aCt44Gr44KI44GO44Gj44GfAAA=' 
# 堀元さんと&#13;味覚は似ている
# b64encoded_data = 'nAEAAAAAAABEMyIRFAAAAAAADgAKAAQAAAAAAAAACQAOAAAAZAAAAAABXgAcABAADAAAAAAAAAAAAAAAAAAAAAAAGAAXAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAHAF4AAAAAAAABFAAAACQAAABEAAAAAAAAARAAAABg////ZP///2j///9G////AAIIJgEAAAAEAAAAFgAAAE5vdG9TZXJpZkpQLUV4dHJhTGlnaHQAAAEAAAAMAAAACAAMAAQACAAIAAAAjAAAADgAAAA0ABgAAAAAABQAAAAQAA8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAQANAAAABgAAAAcAAAAAAAAASQAAAA0AAAABAAEAAQAAAAEAAYABAAAAAAACgAKAAcACAAJAAoAAAAAAAACCCYKAAgABQAGAAcACgAAAADq3c8lAAAA5aCA5YWD44GV44KT44GoDeWRs+immuOBr+S8vOOBpuOBhOOCiwAAAA=='
# 堀元さんという人間と&#13;味覚が似ている
b64encoded_data = 'rAEAAAAAAABEMyIRFAAAAAAADgAKAAQAAAAAAAAACQAOAAAAZAAAAAABXgAcABAADAAAAAAAAAAAAAAAAAAAAAAAGAAXAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAHAF4AAAAAAAABFAAAACQAAABEAAAAAAAAARAAAABg////ZP///2j///9G////AAIIJgEAAAAEAAAAFgAAAE5vdG9TZXJpZkpQLUV4dHJhTGlnaHQAAAEAAAAMAAAACAAMAAQACAAIAAAAjAAAADgAAAA0ABgAAAAAABQAAAAQAA8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAQANAAAABgAAAAcAAAAAAAAASQAAAA0AAAABAAEAAQAAAAEAAYABAAAAAAACgAKAAcACAAJAAoAAAAAAAACCCYKAAgABQAGAAcACgAAAADq3c80AAAA5aCA5YWD44GV44KT44Go44GE44GG5Lq66ZaT44GoDeWRs+immuOBjOS8vOOBpuOBhOOCiwAAAAA='

b64decoded_data = base64.b64decode(b64encoded_data)
print(b64decoded_data)

print("====================================")

# ascii_b64decoded_data = b64decoded_data.decode('ascii', errors='replace')
ascii_b64decoded_data = b64decoded_data.decode('utf-8', errors='backslashreplace')
print(ascii_b64decoded_data)
# dict_data = json.loads(ascii_b64decoded_data)
# print(dict_data)
# h{"mTextParam":{"mAlignment":0,"mDefaultRun":[],"mHeight":0,"mHindiDigits":false,"mIndic":false,"mIsVerticalText":false,"mLeading":-3,"mLigatures":false,"mRTL":false,"mShadowAngle":135,"mShadowBlur":40,"mShadowColor":4144959,"mShadowOffset":7,"mShadowOpacity":75,"mShadowSize":0,"mShadowVisible":false,"mStyleSheet":{"mBaselineOption":{"mParamValues":[[0,0]]},"mBaselineShift":{"mParamValues":[[0,0]]},"mCapsOption":{"mParamValues":[[0,2]]},"mFauxBold":{"mParamValues":[[0,false]]},"mFauxItalic":{"mParamValues":[[0,false]]},"mFillColor":{"mParamValues":[[0,16777215]]},"mFillOverStroke":{"mParamValues":[[0,true]]},"mFillVisible":{"mParamValues":[[0,true]]},"mFontName":{"mParamValues":[[0,"TimesNewRomanPS-BoldMT"]]},"mFontSize":{"mParamValues":[[0,58.826084136962891]]},"mKerning":{"mParamValues":[[0,0]]},"mStrokeColor":{"mParamValues":[[0,16777215]]},"mStrokeVisible":{"mParamValues":[[0,false]]},"mStrokeWidth":{"mParamValues":[[0,1]]},"mText":"Adobe Forum","mTracking":{"mParamValues":[[0,0]]},"mTsumi":{"mParamValues":[[0,0]]}},"mTabWidth":400,"mWidth":0},"mVersion":1}


